### ISSUE TITLE
Don’t say Rubype offers “gradual type checking”

### ISSUE THREAD

**Issue by roryokane** [gogotanaka/Rubype#18]
From [this discussion on Lobsters](https://lobste.rs/s/nniion/rubype_gradual_type_checking_for_ruby/comments/o9ycex#c_o9ycex), and from the [paper](http://scheme2006.cs.uchicago.edu/13-siek.pdf) that one commenter links to, it sounds like “gradual typing” means something different from what this gem does.

Gradual typing means mixing dynamic (run-time) type-checking and static (compile-time) type-checking. This gem does only run-time type-checking.

The following might be better terms for what Rubype implements:
- contracts
- run-time type assertions
- run-time type checking

**Comment by gogotanaka** [comment]
@roryokane Thank you for letting me know. I got your point, you'er right. I've changed the expression : D

Thanks.
